# Only settings that modify the default are listed

# Font and theme settings are in private.toml
general.import = ["./private.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font.normal]
family = "JetBrainsMonoNerdFontMono"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[terminal.shell]
program = "fish"
args = ["-l", "-i"]
# args = ["-l", "-c", "tmux new -As0"]
# args = ["-l", "-c", "zellij a --create $USER@$(hostname)"]

[window]
opacity = 0.90
# Having the title bar to drag is useful when we use two monitors
# decorations = "None"
startup_mode = "Maximized"
# Blur only works on kwin wayland
blur = false

# Keybindings are customized for terminal Emacs.
[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "W", mods = "Control|Shift", action = "Quit" },
    { key = "Q", mods = "Control|Shift", action = "Quit" },
    # Let Zellij handle this for confirmation
    # { key = "Q", mods = "Control", action = "Quit" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward", mode = "~Search" },
    { key = "F", mods = "Control|Shift", action = "SearchForward", mode = "~Search" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "F10", mods = "Control|Shift", action = "ToggleMaximized" },
    { key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
    { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Control|Shift", action = "ScrollLineDown", mode = "~Alt" },
    { key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "End", mods = "Control|Shift", action = "ScrollToBottom" },
    { key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollHalfPageUp" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollHalfPageDown" },
    { key = "Equals", mods = "Control", action = "ReceiveChar" },
    { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = ")", mods = "Control|Shift", action = "ResetFontSize" },
]
