# Keybindings are customized for terminal Emacs.

[keyboard]
bindings = [
    { key = "A", mods = "Alt", chars = "\u001Ba" },
    { key = "B", mods = "Alt", chars = "\u001Bb" },
    { key = "C", mods = "Alt", chars = "\u001Bc" },
    { key = "D", mods = "Alt", chars = "\u001Bd" },
    { key = "E", mods = "Alt", chars = "\u001Be" },
    { key = "F", mods = "Alt", chars = "\u001Bf" },
    { key = "G", mods = "Alt", chars = "\u001Bg" },
    { key = "H", mods = "Alt", chars = "\u001Bh" },
    { key = "I", mods = "Alt", chars = "\u001Bi" },
    { key = "J", mods = "Alt", chars = "\u001Bj" },
    { key = "K", mods = "Alt", chars = "\u001Bk" },
    { key = "L", mods = "Alt", chars = "\u001Bl" },
    { key = "M", mods = "Alt", chars = "\u001Bm" },
    { key = "N", mods = "Alt", chars = "\u001Bn" },
    { key = "O", mods = "Alt", chars = "\u001Bo" },
    { key = "P", mods = "Alt", chars = "\u001Bp" },
    { key = "Q", mods = "Alt", chars = "\u001Bq" },
    { key = "R", mods = "Alt", chars = "\u001Br" },
    { key = "S", mods = "Alt", chars = "\u001Bs" },
    { key = "T", mods = "Alt", chars = "\u001Bt" },
    { key = "U", mods = "Alt", chars = "\u001Bu" },
    { key = "V", mods = "Alt", chars = "\u001Bv" },
    { key = "W", mods = "Alt", chars = "\u001Bw" },
    { key = "X", mods = "Alt", chars = "\u001Bx" },
    { key = "Y", mods = "Alt", chars = "\u001By" },
    { key = "Z", mods = "Alt", chars = "\u001Bz" },
    { key = "A", mods = "Alt|Shift", chars = "\u001BA" },
    { key = "B", mods = "Alt|Shift", chars = "\u001BB" },
    { key = "C", mods = "Alt|Shift", chars = "\u001BC" },
    { key = "D", mods = "Alt|Shift", chars = "\u001BD" },
    { key = "E", mods = "Alt|Shift", chars = "\u001BE" },
    { key = "F", mods = "Alt|Shift", chars = "\u001BF" },
    { key = "G", mods = "Alt|Shift", chars = "\u001BG" },
    { key = "H", mods = "Alt|Shift", chars = "\u001BH" },
    { key = "I", mods = "Alt|Shift", chars = "\u001BI" },
    { key = "J", mods = "Alt|Shift", chars = "\u001BJ" },
    { key = "K", mods = "Alt|Shift", chars = "\u001BK" },
    { key = "L", mods = "Alt|Shift", chars = "\u001BL" },
    { key = "M", mods = "Alt|Shift", chars = "\u001BM" },
    { key = "N", mods = "Alt|Shift", chars = "\u001BN" },
    { key = "O", mods = "Alt|Shift", chars = "\u001BO" },
    { key = "P", mods = "Alt|Shift", chars = "\u001BP" },
    { key = "Q", mods = "Alt|Shift", chars = "\u001BQ" },
    { key = "R", mods = "Alt|Shift", chars = "\u001BR" },
    { key = "S", mods = "Alt|Shift", chars = "\u001BS" },
    { key = "T", mods = "Alt|Shift", chars = "\u001BT" },
    { key = "U", mods = "Alt|Shift", chars = "\u001BU" },
    { key = "V", mods = "Alt|Shift", chars = "\u001BV" },
    { key = "W", mods = "Alt|Shift", chars = "\u001BW" },
    { key = "X", mods = "Alt|Shift", chars = "\u001BX" },
    { key = "Y", mods = "Alt|Shift", chars = "\u001BY" },
    { key = "Z", mods = "Alt|Shift", chars = "\u001BZ" },
    { key = "Q", mods = "Control", action = "Quit" },
    { key = "A", mods = "Control|Shift", chars = "\u001B[65;6u" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward", mode = "~Search" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "F", mods = "Control|Shift", action = "SearchForward", mode = "~Search" },
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "T", mods = "Control|Shift", action = "Quit" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "W", mods = "Control|Shift", action = "Quit" },
    { key = "Key1", mods = "Alt", chars = "\u001B1" },
    { key = "Key2", mods = "Alt", chars = "\u001B2" },
    { key = "Key3", mods = "Alt", chars = "\u001B3" },
    { key = "Key4", mods = "Alt", chars = "\u001B4" },
    { key = "Key5", mods = "Alt", chars = "\u001B5" },
    { key = "Key6", mods = "Alt", chars = "\u001B6" },
    { key = "Key7", mods = "Alt", chars = "\u001B7" },
    { key = "Key8", mods = "Alt", chars = "\u001B8" },
    { key = "Key9", mods = "Alt", chars = "\u001B9" },
    { key = "Key0", mods = "Alt", chars = "\u001B0" },
    { key = "Key3", mods = "Alt|Shift", chars = "\u001B#" },
    { key = "Key4", mods = "Alt|Shift", chars = "\u001B$" },
    { key = "Key5", mods = "Alt|Shift", chars = "\u001B%" },
    { key = "Key6", mods = "Alt|Shift", chars = "\u001B^" },
    { key = "Key8", mods = "Alt|Shift", chars = "\u001B*" },
    { key = "Key0", mods = "Control", action = "ReceiveChar" },
    { key = ")", mods = "Control|Shift", action = "ResetFontSize" },
    { key = "F1", chars = "\u001BOP" },
    { key = "F2", chars = "\u001BOQ" },
    { key = "F3", chars = "\u001BOR" },
    { key = "F4", chars = "\u001BOS" },
    { key = "F5", chars = "\u001B[15~" },
    { key = "F6", chars = "\u001B[17~" },
    { key = "F7", chars = "\u001B[18~" },
    { key = "F8", chars = "\u001B[19~" },
    { key = "F9", chars = "\u001B[20~" },
    { key = "F10", chars = "\u001B[21~" },
    { key = "F11", chars = "\u001B[23~" },
    { key = "F12", chars = "\u001B[24~" },
    { key = "F1", mods = "Shift", chars = "\u001B[1;2P" },
    { key = "F2", mods = "Shift", chars = "\u001B[1;2Q" },
    { key = "F3", mods = "Shift", chars = "\u001B[1;2R" },
    { key = "F4", mods = "Shift", chars = "\u001B[1;2S" },
    { key = "F5", mods = "Shift", chars = "\u001B[15;2~" },
    { key = "F6", mods = "Shift", chars = "\u001B[17;2~" },
    { key = "F7", mods = "Shift", chars = "\u001B[18;2~" },
    { key = "F8", mods = "Shift", chars = "\u001B[19;2~" },
    { key = "F9", mods = "Shift", chars = "\u001B[20;2~" },
    { key = "F10", mods = "Shift", chars = "\u001B[21;2~" },
    { key = "F11", mods = "Shift", chars = "\u001B[23;2~" },
    { key = "F12", mods = "Shift", chars = "\u001B[24;2~" },
    { key = "F1", mods = "Control", chars = "\u001B[1;5P" },
    { key = "F2", mods = "Control", chars = "\u001B[1;5Q" },
    { key = "F3", mods = "Control", chars = "\u001B[1;5R" },
    { key = "F4", mods = "Control", chars = "\u001B[1;5S" },
    { key = "F5", mods = "Control", chars = "\u001B[15;5~" },
    { key = "F6", mods = "Control", chars = "\u001B[17;5~" },
    { key = "F7", mods = "Control", chars = "\u001B[18;5~" },
    { key = "F8", mods = "Control", chars = "\u001B[19;5~" },
    { key = "F9", mods = "Control", chars = "\u001B[20;5~" },
    { key = "F10", mods = "Control", chars = "\u001B[21;5~" },
    { key = "F11", mods = "Control", chars = "\u001B[23;5~" },
    { key = "F12", mods = "Control", chars = "\u001B[24;5~" },
    { key = "F1", mods = "Alt", chars = "\u001B[1;6P" },
    { key = "F2", mods = "Alt", chars = "\u001B[1;6Q" },
    { key = "F3", mods = "Alt", chars = "\u001B[1;6R" },
    { key = "F4", mods = "Alt", chars = "\u001B[1;6S" },
    { key = "F5", mods = "Alt", chars = "\u001B[15;6~" },
    { key = "F6", mods = "Alt", chars = "\u001B[17;6~" },
    { key = "F7", mods = "Alt", chars = "\u001B[18;6~" },
    { key = "F8", mods = "Alt", chars = "\u001B[19;6~" },
    { key = "F9", mods = "Alt", chars = "\u001B[20;6~" },
    { key = "F10", mods = "Alt", chars = "\u001B[21;6~" },
    { key = "F11", mods = "Alt", chars = "\u001B[23;6~" },
    { key = "F12", mods = "Alt", chars = "\u001B[24;6~" },
    { key = "F1", mods = "Super", chars = "\u001B[1;3P" },
    { key = "F2", mods = "Super", chars = "\u001B[1;3Q" },
    { key = "F3", mods = "Super", chars = "\u001B[1;3R" },
    { key = "F4", mods = "Super", chars = "\u001B[1;3S" },
    { key = "F5", mods = "Super", chars = "\u001B[15;3~" },
    { key = "F6", mods = "Super", chars = "\u001B[17;3~" },
    { key = "F7", mods = "Super", chars = "\u001B[18;3~" },
    { key = "F8", mods = "Super", chars = "\u001B[19;3~" },
    { key = "F9", mods = "Super", chars = "\u001B[20;3~" },
    { key = "F10", mods = "Super", chars = "\u001B[21;3~" },
    { key = "F11", mods = "Super", chars = "\u001B[23;3~" },
    { key = "F12", mods = "Super", chars = "\u001B[24;3~" },
    { key = "F10", mods = "Control|Shift", action = "ToggleMaximized" },
    { key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
    { key = "Period", mods = "Alt", chars = "\u001B." },
    { key = "Period", mods = "Alt|Shift", chars = "\u001B>" },
    { key = "Up", mods = "Shift", chars = "\u001B[1;2A" },
    { key = "Up", mods = "Control", chars = "\u001B[1;5A" },
    { key = "Up", mods = "Alt", chars = "\u001B[1;3A" },
    { key = "Up", mode = "~AppCursor", chars = "\u001B[A" },
    { key = "Up", mode = "AppCursor", chars = "\u001BOA" },
    { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Shift", chars = "\u001B[1;2B" },
    { key = "Down", mods = "Control", chars = "\u001B[1;5B" },
    { key = "Down", mods = "Alt", chars = "\u001B[1;3B" },
    { key = "Down", mode = "~AppCursor", chars = "\u001B[B" },
    { key = "Down", mode = "AppCursor", chars = "\u001BOB" },
    { key = "Down", mods = "Control|Shift", action = "ScrollLineDown", mode = "~Alt" },
    { key = "Left", mods = "Shift", chars = "\u001B[1;2D" },
    { key = "Left", mods = "Control", chars = "\u001B[1;5D" },
    { key = "Left", mods = "Alt", chars = "\u001B[1;3D" },
    { key = "Left", mode = "~AppCursor", chars = "\u001B[D" },
    { key = "Left", mode = "AppCursor", chars = "\u001BOD" },
    { key = "Right", mods = "Shift", chars = "\u001B[1;2C" },
    { key = "Right", mods = "Control", chars = "\u001B[1;5C" },
    { key = "Right", mods = "Alt", chars = "\u001B[1;3C" },
    { key = "Right", mode = "~AppCursor", chars = "\u001B[C" },
    { key = "Right", mode = "AppCursor", chars = "\u001BOC" },
    { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
    { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "Space", mods = "Alt", chars = "\u001B" },
    { key = "Space", mods = "Shift", chars = "\u001B[32;2u" },
    { key = "Space", mods = "Control", chars = "\u001B[32;5u" },
    { key = "Home", mods = "Alt", chars = "\u001B[1;3H" },
    { key = "Home", mode = "AppCursor", chars = "\u001BOH" },
    { key = "Home", mode = "~AppCursor", chars = "\u001B[H" },
    { key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "End", mods = "Alt", chars = "\u001B[1;3F" },
    { key = "End", mode = "AppCursor", chars = "\u001BOF" },
    { key = "End", mode = "~AppCursor", chars = "\u001B[F" },
    { key = "End", mods = "Control|Shift", action = "ScrollToBottom" },
    { key = "PageUp", chars = "\u001B[5~" },
    { key = "PageUp", mods = "Alt", chars = "\u001B[5;3~" },
    { key = "PageUp", mods = "Control", chars = "\u001B[5;5~" },
    { key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
    { key = "PageUp", mods = "Shift", mode = "Alt", chars = "\u001B[5;2~" },
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollHalfPageUp" },
    { key = "PageDown", chars = "\u001B[6~" },
    { key = "PageDown", mods = "Alt", chars = "\u001B[6;3~" },
    { key = "PageDown", mods = "Control", chars = "\u001B[6;5~" },
    { key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
    { key = "PageDown", mods = "Shift", mode = "Alt", chars = "\u001B[6;2~" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollHalfPageDown" },
    { key = "Tab", mods = "Shift", chars = "\u001B[Z" },
    { key = "Back", chars = "\u007F" },
    { key = "Back", mods = "Alt", chars = "\u001B\u007F" },
    { key = "Comma", mods = "Alt|Shift", chars = "\u001B<" },
    { key = "Equals", mods = "Control", action = "ReceiveChar" },
    { key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "ReceiveChar" },
    { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "Minus", mods = "Alt|Shift", chars = "\u001B_" },
    { key = "Insert", chars = "\u001B[2~" },
    { key = "Delete", chars = "\u001B[3~" },
    { key = "Slash", mods = "Alt", chars = "\u001B/" },
    { key = "Backslash", mods = "Alt", chars = "\u001B\\" },
    { key = "Backslash", mods = "Alt|Shift", chars = "\u001B|" },
    { key = "Period", mods = "Alt|Shift", chars = "\u001B>" },
]
