#+TITLE: Customizing Alacritty
#+AUTHOR: Swarnendu Biswas
#+EMAIL: swarnendu@cse.iitk.ac.in
#+OPTIONS: author:t date:nil ^:{}
#+STARTUP: showeverything indent nonum align showstars nohideblocks entitiespretty

* Alacritty

=Alacritty= is a terminal emulator. It is the drawing on your GUI that lets you do things as if you were on the console. You can use the following PPA to install =Alacritty= for Ubuntu:

#+begin_src shell
sudo add-apt-repository ppa:aslatter/ppa -y
sudo apt update
#+end_src

The following is an alternative way to install it.

#+begin_src shell
sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
cargo install alacritty

# The Alacritty config file is at `$HOME/.config/alacritty/alacritty.yml`

sudo cp ./alacritty/Alacritty.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install ./alacritty/Alacritty.desktop
sudo update-desktop-database

mkdir -p ~/.bash_completion
cp ./alacritty/alacritty.bash ~/.bash_completion/alacritty
echo "source ~/.bash_completion/alacritty" >> ~/.bashrc

cd ~
mkdir -p $fish_complete_path[1]
cp extra/completions/alacritty.fish $fish_complete_path[1]/alacritty.fish
echo "source ~/.config/alacritty/alacritty.fish" >> ~/.config/fish/config.fish

# Check if the terminfo file is installed
infocmp alacritty
sudo tic -xe alacritty,alacritty-direct ./alacritty/alacritty.info
#+end_src

** Themes

#+begin_src shell
mkdir -p $XDG_CONFIG_HOME/alacritty/themes/
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
#+end_src

** Alacritty + Tmux key integration

=Alacritty= can send hex codes for shortcuts you define. So for example you can send a hex code for the shortcut "c-f v" that is: 0x06 0x76. There are many ways to find it out. One of them is the tool =xxd=. If you run ~xxd -psd~ and hit "c-f v" and then enter and finally ~c-c~ to exit, it outputs the following:

#+begin_src shell
$ xxd -psd
^Fv
06760a^C
#+end_src

What matters is the sequence ~06760a^C~ where:
=06 -> c-f=,
=76 -> v=
=0a -> return=
=^C -> c-c=

From here, we know that ~0x06 0x76~ corresponds to =c-f v=.

The next step is to add a line to ~key_binding~ setting in =Alacritty=: ~{ key: D, mods: Command, chars: "\x06\x76" }~.
