# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Disable the blank line at the start of the prompt
add_newline = false
right_format = '$cmd_duration$status'
command_timeout = 1000

[aws]
disabled = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󱟞 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 25
style = 'red'
discharging_symbol = '💦 '

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[cmd_duration]
disabled = false

# [character]
# success_symbol = '[➜](bold green) '
# error_symbol = '[✗](bold red) '
# success_symbol = '[](bold fg:color_green)'
# error_symbol = '[](bold fg:color_red)'

[directory]
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[gcloud]
disabled = true

[hostname]
ssh_only = false

[memory_usage]
disabled = true

[os]
disabled = true
style = "bg:subtext1 fg:base"

[os.symbols]
Arch = '󰣇'
Fedora = ""
Gentoo = ""
Linux = ""
openSUSE = ""
Ubuntu = ""
Windows = ""
Unknown = '󰠥'

[shell]
disabled = false
bash_indicator = ""
powershell_indicator = ""
cmd_indicator = ""
fish_indicator = '󰈺'

[sudo]
disabled = false

[time]
disabled = true

[username]
show_always = true
