# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# Use the color palette
palette = "dracula"
right_format = '$cmd_duration$status'
command_timeout = 2000

[aws]
disabled = true

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󱟞 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 25
style = 'red'
discharging_symbol = '💦 '

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 80
style = "bold green"

[character]
disabled = false

[cmd_duration]
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[directory]
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[gcloud]
disabled = true

[hostname]
ssh_only = false

[memory_usage]
disabled = true

[os]
disabled = false

[os.symbols]
Arch = '󰣇 '
Fedora = " "
Gentoo = " "
Linux = " "
openSUSE = " "
Ubuntu = " "
Windows = " "
Unknown = '󰠥 '

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[shell]
disabled = false
bash_indicator = ""
powershell_indicator = ""
cmd_indicator = ""
fish_indicator = '󰈺'

[sudo]
disabled = false

[time]
disabled = true

[username]
show_always = true
